# Documentation - https://github.com/actions/labeler

# General Labels
'Build | Project System':
  - changed-files:
    - any-glob-to-any-file:
      - '.github/*'
      - '.github/**/*'
      - '*.xcconfig'
      - '**/*.xcconfig'
      - '*.xcodeproj/*'
      - '**/*.xcodeproj/*'
      - 'Makefile'
      - '.editorconfig'
      - '.gitignore'

'Dependencies':
  - changed-files:
    - any-glob-to-any-file:
      - 'Dependencies/*'
      - 'Dependencies/**/*'
      - '.gitmodules'

'Documentation':
  - changed-files:
    - any-glob-to-any-file:
      - '*.md'
      - '**/*.md'
      - 'LICENSE'

'GUI/UIKit':
  - changed-files:
    - any-glob-to-any-file:
      - 'ReStore/Views/*'
      - 'ReStore/Views/**/*'
      - 'ReStoreApp/App Detail/*.swift'
      - 'ReStoreApp/Browse/*.swift'
      - 'ReStoreApp/Authentication/*.swift'
      - 'ReStoreApp/My Apps/*.swift'
      - 'ReStoreApp/News/*.swift'
      - 'ReStoreApp/Settings/*.swift'
      - 'ReStoreApp/Sources/*.swift'

'Resources | Assets':
  - changed-files:
    - any-glob-to-any-file:
      - 'ReStoreApp/Resources/*'
      - 'ReStoreApp/Resources/**/*'
      - 'ReStoreApp/Base.lproj/*'
      - 'ReStoreApp/Base.lproj/**/*'
      - 'ReStoreBackup/Assets.xcassets/*'
      - 'ReStoreBackup/Assets.xcassets/**/*'
      - 'ReStoreWidget/Assets.xcassets/*'
      - 'ReStoreWidget/Assets.xcassets/**/*'

# Tools / Features
'Backup':
  - changed-files:
    - any-glob-to-any-file:
      - 'ReStoreBackup/*'
      - 'ReStoreBackup/**/*'

'Widget':
  - changed-files:
    - any-glob-to-any-file:
      - 'ReStoreWidget/*'
      - 'ReStoreWidget/**/*'

'App Detail':
  - changed-files:
    - any-glob-to-any-file:
      - 'ReStoreApp/App Detail/*'
      - 'ReStoreApp/App Detail/**/*'

'App IDs':
  - changed-files:
    - any-glob-to-any-file:
      - 'ReStoreApp/App IDs/*'
      - 'ReStoreApp/App IDs/**/*'

'Authentication':
  - changed-files:
    - any-glob-to-any-file:
      - 'ReStoreApp/Authentication/*'
      - 'ReStoreApp/Authentication/**/*'

'Browse':
  - changed-files:
    - any-glob-to-any-file:
      - 'ReStoreApp/Browse/*'
      - 'ReStoreApp/Browse/**/*'

'Managing Apps':
  - changed-files:
    - any-glob-to-any-file:
      - 'ReStoreApp/Managing Apps/*'
      - 'ReStoreApp/Managing Apps/**/*'

'My Apps':
  - changed-files:
    - any-glob-to-any-file:
      - 'ReStoreApp/My Apps/*'
      - 'ReStoreApp/My Apps/**/*'

'News':
  - changed-files:
    - any-glob-to-any-file:
      - 'ReStoreApp/News/*'
      - 'ReStoreApp/News/**/*'

'Settings':
  - changed-files:
    - any-glob-to-any-file:
      - 'ReStoreApp/Settings/*'
      - 'ReStoreApp/Settings/**/*'

'Sources':
  - changed-files:
    - any-glob-to-any-file:
      - 'ReStoreApp/Sources/*'
      - 'ReStoreApp/Sources/**/*'

# Core Components
'Core':
  - changed-files:
    - any-glob-to-any-file:
      - 'AltStoreCore/*'
      - 'AltStoreCore/**/*'

'Shared':
  - changed-files:
    - any-glob-to-any-file:
      - 'Shared/*'
      - 'Shared/**/*'

'ReStore':
  - changed-files:
    - any-glob-to-any-file:
      - 'ReStore/*'
      - 'ReStore/**/*'

# Other Core Components
'Operations':
  - changed-files:
    - any-glob-to-any-file:
      - 'ReStoreApp/Operations/*'
      - 'ReStoreApp/Operations/**/*'

'Intents':
  - changed-files:
    - any-glob-to-any-file:
      - 'ReStoreApp/Intents/*'
      - 'ReStoreApp/Intents/**/*'

'Permissions':
  - changed-files:
    - any-glob-to-any-file:
      - 'ReStoreApp/Permissions/*'
      - 'ReStoreApp/Permissions/**/*'

'App Lifecycle':
  - changed-files:
    - any-glob-to-any-file:
      - 'ReStoreApp/AppDelegate.swift'
      - 'ReStoreApp/SceneDelegate.swift'
      - 'ReStoreApp/TabBarController.swift'
      - 'ReStoreApp/LaunchViewController.swift'
      - 'ReStoreApp/AppConstants.swift'
